server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080

positions:
  filename: /var/tmp/positions.yaml

clients:
  - url: http://loki.minikube.cloud/loki/api/v1/push

scrape_configs:  
- job_name: journal
  journal:
    path: /var/log/journal
    max_age: 12h
    labels:
      job: systemd-journal
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
    - source_labels: ['__journal__hostname']
      target_label: 'hostname'
    - source_labels: ['__journal_container_tag']
      target_label: 'container'

# - job_name: containers
#   static_configs:
#   - targets:
#       - localhost
#     labels:
#       job: containerlogs
#       __path__: /rootfs/var/lib/containers/storage/overlay-containers/*/userdata/ctr.log

#   pipeline_stages:
#   - json:
#       expressions:
#         output: log
#         stream: stream
#         attrs:
#   - json:
#       expressions:
#         tag:
#       source: attrs
#   - regex:
#       expression: (?P<container_name>(?:[^|]*[^|]))
#       source: tag
#   - timestamp:
#       format: RFC3339Nano
#       source: time
#   - labels:
#       # tag:
#       stream:
#       container_name:
#   - output:
#       source: output